# Generated by Django 5.2.7 on 2025-10-24 09:23

from django.db import migrations


def fill_item_prices(apps, schema_editor):
    OrderItems = apps.get_model('foodcartapp', 'OrderItems')
    for oi in OrderItems.objects.select_related('product'):
        if oi.price is None:
            oi.price = oi.product.price
            oi.save(update_fields=['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitems_price'),
    ]

    operations = [
        migrations.RunPython(fill_item_prices, migrations.RunPython.noop),
    ]
