# Generated by Django 5.2.7 on 2025-12-08 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_fill_orderitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('ASSEMBLING', 'Сборка'), ('DELIVERING', 'Доставка'), ('FINISHED', 'Завершён')], db_index=True, default='NEW', max_length=12),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена в момент заказа'),
            preserve_default=False,
        ),
    ]
