# Generated by Django 5.2.7 on 2025-12-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличные'), ('non-cash', 'безнал')], db_index=True, default='cash', max_length=10, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('ASSEMBLING', 'Сборка'), ('DELIVERING', 'Доставка'), ('FINISHED', 'Завершён')], db_index=True, default='NEW', max_length=12, verbose_name='статус'),
        ),
    ]
