# Generated by Django 5.2.7 on 2025-12-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_cooking_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='адрес')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адреса',
            },
        ),
    ]
