# Generated by Django 5.2.9 on 2025-12-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_payment_method_alter_order_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
